nknorg/nkn-tuna-session

README.md, examples/throughput/main.go, go.mod, go.sum
Also fix gomobile compatibility when including tuna
=> Add cli option to change session mtu

examples/http/main.go, examples/throughput/main.go
=> Add cli flag for price

go.mod, go.sum
=> Upgrade tuna version for true random subscriber selection

client.go, go.mod, go.sum
=> Close session if all conn are closed

client.go
=> Do not set write deadline to prevent partial data write

client.go, conn.go, message.go
=> Add conn read/write to prevent concurrent write bad data

go.mod, go.sum
=> Fix late payment when traffic stops for a while (by upgrading tuna)

go.mod, go.sum
=> Upgrade sdk version to greatly reduce RAM usage

client.go, message.go
=> Add GetPubAddrs method to get exit info

client.go, config.go, go.mod, go.sum
=> Add config for downloading geo db

go.mod, go.sum
=> Upgrade tuna version

client.go, message.go
=> Add message size limit to restrict ram usage caused by abnormal conn

client.go, examples/throughput/main.go, go.mod, go.sum, node.go
=> Add weight sorting to avoid all tuna connect to same node

go.mod, go.sum
=> Upgrade tuna to 2136231

client.go, go.mod, go.sum
=> Add rotate api to change tuna node

client.go
=> Add api to set config after created

go.mod, go.sum
=> Upgrade tuna version to 2077fdc

go.mod, go.sum
=> Upgrade tuna version to 38dae81

client.go
=> Fix incompatible API with new tuna version

client.go, config.go, examples/throughput/main.go, message.go
=> Add write timeout and use nkn-sdk-go dial config type

go.mod, go.sum
=> upgrade nkn sdk and tuna

client.go, config.go
=> Add config for percentage based nanopay txn fee

README.md, go.mod, go.sum
=> Update nkn-sdk-go and tuna version

README.md, client.go, examples/http/main.go, examples/throughput/main.go, go.mod, go.sum
=> Add OnConnect() API so Listen() could return earlier

go.mod, go.sum
=> Upgrade tuna version to c866b7b

client.go
=> Fix local and remote connID might be inconsistent

client.go, config.go, test/pub.go, test/reconnect_test.go, test/tunasession.go
Signed-off-by: bill fort <fxbao@hotmail.com>
=> Implement of reconnecting when connection(s) disconnect exceptionally
